from app.agent.router.types import Intent, ToolCapability


GLOBAL_TOOL_REGISTRY = {
    "search_metadata": ToolCapability(
        name="search_metadata",
        intents={Intent.PHOTO_SEARCH, Intent.PHOTO_ORGANIZATION},
        description="Search indexed photos using exact metadata matches like year, month, location, and favorite status.",
        required_inputs=set(),
        optional_inputs={"date_range", "location", "favorites", "year", "month", "is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
    "search_people": ToolCapability(
        name="search_people",
        intents={Intent.PHOTO_SEARCH, Intent.PHOTO_ORGANIZATION},
        description="Search for photos containing specific identified people by their names.",
        required_inputs={"names"},
        optional_inputs={"min_confidence", "is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
    "search_captions": ToolCapability(
        name="search_captions",
        intents={Intent.PHOTO_SEARCH},
        description="Search for photos by matching user-provided captions and tags using full-text search.",
        required_inputs={"query"},
        optional_inputs={"is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
    "semantic_search": ToolCapability(
        name="semantic_search",
        intents={Intent.PHOTO_SEARCH},
        description="Perform AI visual search using semantic embeddings to find photos conceptually matching the text query.",
        required_inputs={"text_query"},
        optional_inputs={"top_k", "is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="medium",
        supports_batch=False,
        idempotent=True,
    ),
    "search_albums": ToolCapability(
        name="search_albums",
        intents={Intent.PHOTO_SEARCH, Intent.PHOTO_ORGANIZATION},
        description="Search for photos belonging to albums that match the query.",
        required_inputs={"query"},
        optional_inputs={"is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
    "search_ocr": ToolCapability(
        name="search_ocr",
        intents={Intent.PHOTO_SEARCH},
        description="Search for photos containing specific text using OCR (Optical Character Recognition) indexes.",
        required_inputs={"query"},
        optional_inputs={"is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
    "similar_image": ToolCapability(
        name="similar_image",
        intents={Intent.PHOTO_SEARCH},
        description="Find visually similar photos based on a target photo ID using image embeddings.",
        required_inputs={"photo_id"},
        optional_inputs={"top_k", "is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="medium",
        supports_batch=False,
        idempotent=True,
    ),
    "search_events": ToolCapability(
        name="search_events",
        intents={Intent.PHOTO_SEARCH},
        description="Find photos associated with curated events and dates matching the query.",
        required_inputs={"query"},
        optional_inputs={"is_locked"},
        read_only=True,
        destructive=False,
        external_side_effect=False,
        estimated_cost="low",
        supports_batch=False,
        idempotent=True,
    ),
}
